---
title: "blaa"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(stringr)
library(data.table)

#df_tags1 <- read_csv("Desktop/NLP/scraping/df_tags.csv")

```

```{r}
library(readr)
# nurse <- read_csv("Desktop/NLP/scraping/nurse.csv")
# nurse10 <- read_csv("Desktop/NLP/scraping/nurse10.csv")
# engineer1 <- read_csv("Desktop/NLP/scraping/engineer.csv")
# designer2 <- read_csv("Desktop/NLP/scraping/designer2.csv")
# geo2 <- read_csv("Desktop/NLP/scraping/geo2.csv")
# scientist <- read_csv("Desktop/NLP/scraping/scientist.csv")
# doctor <- read_csv("Desktop/NLP/scraping/doctor.csv")
# executive <- read_csv("Desktop/NLP/scraping/executive.csv")
# computerscience <- read_csv("Desktop/NLP/scraping/computerscience.csv")
# teacher <- read_csv("Desktop/NLP/scraping/teacher.csv")
# socialworker <- read_csv("~/Desktop/NLP/scraping/socialworker.csv")
# 
# 
# setwd("~/Desktop/NLP/scraping/Uncleaned Data CC")
# carpenter1 <- read_csv("Desktop/NLP/scraping/Uncleaned Data CC/carpenter1.csv")
# concreter2 <- read_csv("Desktop/NLP/scraping/Uncleaned Data CC/concreter2.csv")
# softwaredeveloper1 <- read_csv("Desktop/NLP/scraping/Uncleaned Data CC/softwaredeveloper1.csv")
# softwaredeveloper2 <- read_csv("Desktop/NLP/scraping/Uncleaned Data CC/softwaredeveloper2.csv")
# constructionmanager1 <- read_csv("constructionmanager1.csv")

df_final <- read_csv("Desktop/NLP/scraping/df_final.csv", col_types = cols(crawl_timestamp = col_skip(), inferred_iso2_lang_code = col_skip(), inferred_iso3_lang_code = col_skip(), job_board = col_skip(), job_post_lang = col_skip(), postdate_yyyymmdd = col_skip(), uniq_id = col_skip(), url = col_skip(), salary_offered = col_skip(), inferred_salary_currency = col_skip(), inferred_salary_to = col_skip(), inferred_salary_from = col_skip(), contact_email = col_skip(), html_job_description = col_skip(), fitness_score = col_skip(), inferred_country = col_skip(), inferred_state = col_skip(), inferred_city = col_skip(), postdate_in_indexname_format = col_skip(), duplicate_status = col_skip(), latest_expiry_check_date = col_skip(), last_expiry_check_date = col_skip(), has_expired = col_skip(), geo = col_skip(), site_name = col_skip(), domain = col_skip(), inferred_salary_time_unit = col_skip()))

```

```{r}
# d <- nurse
# d<-d[!(d$Description=="None"),]
# d <- d %>% distinct()
# 
# nurse <- nurse10
# d10<-d10[!(d10$Description=="None"),]
# d10 <- d10 %>% distinct()
# d10$Sector = "Nurse"
# 
# engineer2 <- read_csv("Desktop/NLP/scraping/Uncleaned Data CC/engineer2.csv")
# engineer <- rbind(engineer1, engineer2)
# engineer <-engineer[!(engineer$Description=="None"),]
# engineer <- engineer %>% distinct()
# engineer$Sector = "Engineer"
# 
# des <- designer2
# des<- des[!(des$Description=="None"),]
# des <- des %>% distinct()
# des$Sector = "Designer"
# 
# geo <- geo2
# geo<- geo[!(geo$Description=="None"),]
# geo <- geo %>% distinct()
# geo$Sector = "Geologist"
# 
# sci <- scientist
# sci<- sci[!(sci$Description=="None"),]
# sci <- sci %>% distinct()
# sci$Sector = "Scientist"
# 
# doc <- doctor
# doc<- doc[!(doc$Description=="None"),]
# doc <- doc %>% distinct()
# doc$Sector = "Doctor"
# 
# exe <- executive
# exe<- exe[!(exe$Description=="None"),]
# exe <- exe %>% distinct()
# exe$Sector = "Executive"
# 
# data <- socialworker
# for(i in data) {
#   data <- data[!(data$Description=="None"),]
#   data <- data %>% distinct()
#   #data$Sector = "librarian"
# }
# socialworker <- data 

# technology <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/technology.csv")
# technology$Sector = "Technology"
# teacher <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/teacher.csv")
# teacher$Sector = "Teacher"
# principal <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/school+principal.csv")
# principal$Sector = "School Principal"
# mechanic2 <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/mechanic2.csv")
# mechanic <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/mechanic.csv")
# mechanic <- rbind(mechanic, mechanic2)
# mechanic$Sector = "Mechanic"
# librarian <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/librarian1.csv")
# librarian$Sector = "Librarian"
# receptionist <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/receptionist.csv")
# receptionist$Sector = "Receptionist"
# dentalassis <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/dental assistent.csv")
# dentalassis$Sector = "Dental Assistant"
# physician <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/physician.csv")
# physician$Sector = "Physician"
#generalpractitioner <- read_csv("Desktop/NLP/scraping/general+practitioner.csv")




#datafull <- rbind(carpenter, concreter, constructionmanager, d10, des, doc, engineer, exe, geo, joiner, librarian, mechanic, painter, principal, sci, skilledlabourer, socialworker, softwaredeveloper, softwareengineer, sparky, teacher, technology, receptionist, dentalassis, physician)
datafull <- rbind(datafull, generalpractitioner)
datafull <- datafull[!(datafull$Description=="None"),]
datafull <- datafull %>% distinct()
write.csv(datafull, 'dataG25nov.csv')


```

```{r}
# setwd('/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC')
# sparky <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/sparky1.csv")
# sparky$Sector = "Sparky"
# softwareengineer <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/softwareengineer1.csv")
# softwareengineer$Sector = "Softwareengineer"
# softwaredeveloper <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/softwaredeveloper1.csv")
# softwaredeveloper$Sector = "Softwaredeveloper"
# skilledlabourer <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/skilledlabourer1.csv")
# skilledlabourer$Sector = "Skilledlabourer"
# painter <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/painter1.csv")
# painter$Sector = "Painter"
# joiner <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/joiner1.csv")
# joiner$Sector = "Joiner"
# geologist <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/geologist.csv")
# geologist$Sector = "Geologist"
# constructionmanager <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/constructionmanager1.csv")
# constructionmanager$Sector = "Constructionmanager"
# concreter <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/concreter2.csv")
# concreter$Sector = "Concreter"
# carpenter <- read_csv("/Users/carolinetvergaard/Desktop/NLP/scraping/Uncleaned Data CC/carpenter1.csv")
# carpenter$Sector = "Carpenter"










```


```{r}

medical <- subset(df_seek_30_csv, category=="Healthcare & Medical")
nurse2 <- medical[str_detect(medical$job_title, "nurs"), ]
nurse3 <- medical[medical$job_title %like% "Nurse", ] #552
doctor <- medical[medical$job_title %like% "Resident", ]

librarian1 <- df_seek_30_csv[df_seek_30_csv$job_title %like% "Librarian", ]
surgeon <- df_seek_30_csv[df_seek_30_csv$job_title %like% "Surgeon", ]

# 
# # Load the package required to read JSON files.
# install.packages("rjson")
# library("rjson")
# 
# # Give the input file name to the function.
# result <- fromJSON(file = "marketing_sample_for_seek_au-seek_au_jobs__20200101_20200331.json")
# result
# 
# # Convert JSON file to a data frame.
# json_data_frame <- as.data.frame(result)
# 
# 
# seek_au <- read_csv("~/Desktop/NLP/scraping/marketing_sample_for_seek_au-seek_au_jobs__20200101_20200331.csv")
```



```{r}

# doctor <- read_csv("Desktop/NLP/scraping/doctor.csv")
# doc <- doctor
# doc<- doc[!(doc$Description=="None"),]
# doc <- doc %>% distinct()
# doc$Sector = "Doctor"
# write.csv(doc, 'doc.csv')
# 
# write.csv(e10, 'e10.csv')
# write.csv(d10, 'd10.csv')
# write.csv(des, 'des.csv')
# write.csv(sci, 'sci.csv')
# write.csv(doc, 'doc.csv')
# write.csv(exe, 'exe.csv')
write.csv(datafull, 'dataG24nov.csv')
write.csv(df_final, 'df_final_clean.csv')
```

```{r}
library(ggplot2)
ggplot(data=df_seek_30_csv, aes(x=category, y=gender_bias, fill = category)) +
  stat_summary_bin(fun = "mean", geom = "bar")

sp <- ggplot(df_seek_30_csv, aes(x=gender_bias, y=him_her, label=rownames(job_title)))+
  geom_point()+ 
  group_by(df_seek_30_csv$category)
# Add texts
sp + geom_text(label=rownames(df_seek_30_csv$job_title))
# Change the size of the texts
sp + geom_text(size=6)
# Change vertical and horizontal adjustement
sp +  geom_text(hjust=0, vjust=0)
# Change fontface. Allowed values : 1(normal),
# 2(bold), 3(italic), 4(bold.italic)
sp + geom_text(aes(fontface=2))

library(hrbrthemes)

# mtcars dataset is natively available in R
# head(mtcars)

install.packages("hrbrthemes")
library(hrbrthemes)
# A basic scatterplot with color depending on Species
ggplot(df_seek_30_csv , aes(x=man_woman, y=him_her, color=category)) + 
    geom_point(size=6) +
    theme_ipsum()

ggplot(df_seek_30_csv, aes(x= man_woman, y= him_her, colour=category, label=category)) + 
  geom_point(size = 2,alpha = 0.6) +
  theme_bw()+
  geom_text(aes(label=category),hjust=0, vjust=0)

df <- df_seek_30_csv

df %>% group_by(category) %>% 
  summarise(mean.gender=mean(gender_bias)) %>% 
  ggplot(aes(mean.gender,mean.gender,group=category)) + 
  geom_point()+
  geom_text(aes(label=category),hjust=0, vjust=0)
```

```{r}

ggplot(data=df_tags, aes(x=Sector, y=man_woman, fill = Sector)) +
  geom_bar(stat="identity")

df_tags1 %>% group_by(Sector) %>% 
  summarise(mean.gender=mean(man_woman)) %>% 
  ggplot(aes(mean.gender,mean.gender, color=Sector)) + 
  geom_point()+
  geom_text(aes(label=Sector),hjust=0, vjust=0)

```
```{r}

mtcars <- df_tags

theme_set(theme_bw())  
# Data Prep
#data("mtcars")  # load data
#mtcars$`car name` <- rownames(mtcars)  # create new column for car names
mtcars$man_woman_z <- round((mtcars$man_woman - mean(mtcars$man_woman))/sd(mtcars$man_woman), 2)  # compute normalized mpg
mtcars$Sector <- ifelse(mtcars$man_woman_z < 0, "below", "above")  # above / below avg flag
df_tags <- df_tags[order(df_tags$man_woman), ]  # sort
mtcars$Sector <- factor(mtcars$Sector, levels = mtcars$Sector)  # convert to factor to retain sorted order in plot.

df_tags <- df_tags[order(df_tags$man_woman), ]
# Diverging Barcharts
ggplot(df_tags, aes(x=Sector, y=man_woman, label=man_woman)) + 
  geom_bar(stat='summary', aes(fill=Sector), width=.5)  +
  coord_flip()

ggplot(df_tags1, aes(x=Sector, y=man_woman, label=man_woman)) + 
  geom_bar(stat='summary', aes(fill=Sector), width=.5)  +
  coord_flip()

```



```{r}
ggplot(df_tags, aes(x=Sector, y=father_mother, label=father_mother)) + 
  geom_bar(stat='summary', aes(fill=Sector), width=.5)  +
  coord_flip()
```


```{r}
ggplot(df_seek_30_csv, aes(x=category, y=gender_bias, label=gender_bias)) + 
  geom_bar(stat='summary', width=.5)  +
  coord_flip()
```

